packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@ai-sdk/openai-compatible": ^3.0.39
  "@ai-sdk/provider": ^4.0.8
  "@nestjs/common": ^12.0.1
  "@nestjs/core": ^12.0.1
  "@nestjs/platform-fastify": ^12.0.1
  "@prisma/client": ^7.10.0
  "@rspress/core": ^2.0.21
  "@tanstack/react-query": ^5.102.8
  "@types/node": ^24.13.3
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.5
  "@vitejs/plugin-react": ^6.1.1
  ai: ^7.0.83
  prisma: 8.0.0-rc.12
  react: ^19.2.8
  react-dom: ^19.2.8
  react-router: ^8.3.0
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  tsx: ^4.23.12
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
  void: ^0.10.12
  zod: ^4.5.2
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - zod@4.5.2
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  workerd: true
